package com.soma.app.backendrepo.error_handling

enum class ErrorCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_NOT_VERIFIED,
    BAD_CREDENTIALS,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    INVALID_TOKEN,
    INVALID_EMAIL,
    INVALID_INPUT,
    WEAK_PASSWORD,
    SHORT_PASSWORD,
    TOKEN_EXPIRED,
    JWT_TOKEN_EXPIRED,
    PASSWORD_MISMATCH,
    OLD_PASSWORD_DETECTED,
    TOKEN_NOT_FOUND,
    FORBIDDEN,
    UNAUTHORIZED,
    EMAIL_NOT_FOUND,
    ADDRESS_ALREADY_EXISTS
}